name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download release tarball
        run: |
          curl -L "https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.tag }}.tar.gz" -o source.tar.gz

      - name: Compute SHA256
        id: sha
        run: |
          SHA=$(shasum -a 256 source.tar.gz | awk '{print $1}')
          echo "sha256=$SHA" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          sed -i.bak \
            -e "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.tag }}.tar.gz\"|" \
            -e "s|sha256 \".*\"|sha256 \"${{ env.sha256 }}\"|" \
            Formula/smoothscrolld.rb
          rm -f Formula/smoothscrolld.rb.bak
          echo "✅ Updated Formula/smoothscrolld.rb with new URL and SHA256"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Formula/smoothscrolld.rb
          git commit -m "chore: update formula for ${{ env.tag }}"
          git push
